go.mod, go.sum, noise/noise.go, noise/noise_test.go
Noise for X25519Key sender and recipient.
The cipher suite used is:
Curve25519 ECDH, ChaCha20-Poly1305 AEAD, BLAKE2b hash.
The handshake uses the KK pattern:
K = Static key for initiator Known to responder
K = Static key for responder Known to initiator
The order of the handshake writes/reads should be:
(1) Initiator: HandshakeWrite
(2) Responder: HandshakeRead
(3) Initiator: HandshakeRead
(4) Responder: HandshakeWrite
=> Noise protocol for keys.X25519Key

edx25519_test.go, keyring/README.md, keyring/auth_test.go, keyring/example_test.go, keyring/fs.go, keyring/fs_test.go, keyring/keyring.go, keyring/keyring_test.go, keyring/mem.go, keyring/mem_test.go, keyring/store.go, saltpack/README.md, saltpack/encrypt_examples_test.go, saltpack/encrypt_test.go, saltpack/signcrypt_test.go, secret/secret_test.go, secret/store.go, secret/store_test.go, store.go, store_test.go
Keyring should be a struct. The interface is Store.
=> keyring: Keyring{}

user/search_test.go, user/store_test.go, user/user.go, user/user_test.go
Rename user.NewUser to user.New.
=> user: NewUser to user.New

keyring/cmd/keyring/main.go, keyring/fs.go, keyring/keyring.go, keyring/keyring_darwin.go, keyring/keyring_linux.go, keyring/keyring_test.go, keyring/keyring_windows.go, keyring/mem.go, keyring/store.go
Shows IDs from keyring.
Helpful for debugging.
=> keyring: cmd to show IDs

ds/document.go, edx25519.go, encoding/encode.go, json/marshal.go, keyring/keyring.go, link/service.go, noise/noise.go, saltpack/saltpack.go, secret/secret.go, sigchain.go, statement.go, store.go, user/user.go, util/request.go, x25519.go
=> Linting for godoc

address_test.go, edx25519_test.go, id.go, key.go, keyring.go, keyring_test.go, parse.go, saltpack/encrypt.go, saltpack/encrypt_examples_test.go, saltpack/encrypt_test.go, saltpack/saltpack.go, saltpack/sign.go, saltpack/sign_examples_test.go, saltpack/sign_test.go, saltpack/signcrypt.go, saltpack/signcrypt_test.go, sigchainstore_test.go, store.go, store_test.go
=> Saltpack refactor

keyring/auth.go, keyring/export.go, keyring/export_test.go, keyring/fs.go, keyring/keyring.go, keyring/keyring_darwin.go, keyring/keyring_linux.go, keyring/keyring_test.go, keyring/keyring_windows.go, keyring/mem.go, keyring/store.go
=> keyring: List, Export

link/https.go, link/https_test.go
Allow https://example.com/.well-known/keyspub.txt
=> link: HTTPS .well-known

keyring/auth_test.go, keyring/keyring.go, keyring/keyring_test.go
=> keyring: Status

keyring/README.md, keyring/auth.go, keyring/auth_test.go, keyring/copy_test.go, keyring/example_test.go, keyring/keyring.go, keyring/keyring_test.go, keyring/mem.go, keyring/provision.go, keyring/secretbox.go, saltpack/README.md
=> keyring: Auth.ID

keyring/README.md, keyring/auth.go, keyring/auth_test.go, keyring/cmd/keyring/main.go, keyring/copy.go, keyring/copy_test.go, keyring/example_test.go, keyring/fs.go, keyring/fs_test.go, keyring/keyring.go, keyring/keyring_darwin.go, keyring/keyring_linux.go, keyring/keyring_test.go, keyring/keyring_windows.go, keyring/mem.go, keyring/options.go, keyring/provision.go, keyring/store.go
keyring.New accepts Options, including Store with service name.
=> keyring: Options, Store(service)

encoding/parse.go, keyring/auth_test.go, keyring/encrypt_test.go, keyring/item.go, keyring/item_test.go, keyring/keyring_test.go, keyring/secretbox.go, keyring/store.go, private_test.go, secretbox.go, secretbox_test.go
=> SecretBox test vectors

link/twitter.go, link/twitter_test.go, user/request_test.go, user/search_test.go, user/store_test.go, user/user.go, user/user_test.go
Use mobile.twitter.com for getting statements.
=> Fix Twitter

keyring/fs.go, keyring/fs_test.go, keyring/fsv.go, keyring/fsv_test.go, keyring/mem_test.go, keyring/store.go, keyring/store_test.go, tsutil/tsutil.go, tsutil/tsutil_test.go
Can be used to backup/sync to remote backends.
=> keyring: FSV (filesystem versioned) store

encoding/README.md, encoding/encode.go, encoding/encode_test.go, encoding/options.go
```go
encoding.MustEncode(RandBytes(16), encoding.Base32, encoding.NoPadding())
```
=> encoding: EncodeOptions

ds/changes_test.go, keyring/copy_test.go, rand.go, rand_test.go, secret/secret.go, secret/secret_test.go
=> RandTempFile

ds/changes_test.go, ds/document.go, ds/document_test.go, ds/documents.go, ds/mem.go, ds/mem_test.go, ds/options.go, ds/spew.go, ds/spew_test.go, keyring/store.go, sigchainstore.go, user/search.go, user/search_test.go, user/store.go
```go
ds.Documents(context.TODO(), "sigchain", ds.Prefix(kid.String()))
```
=> ds: DocumentOptions

ds/changes.go, ds/changes_test.go, ds/document.go, ds/documents.go, ds/iterator.go, ds/mem.go, ds/mem_test.go, ds/path.go
New Changes interface.
Also support nested collections.
=> ds: Changes

user/store.go, user/store_test.go
The user store result user could be stale after a revoke and new statement.
=> user: Fix revoke+new update stale user

docs/mem.go, edx25519.go, edx25519_test.go
Also have increment from mem match server impl.
=> edx25519: JSON marshal seed

docs/document_test.go, docs/events/events_test.go, docs/mem_test.go, keyring/backup_test.go, secret/secret_test.go, sigchain_test.go, sigchainstore_test.go, statement.go, statement_example_test.go, statement_test.go, tsutil/clock.go, tsutil/tsutil.go, tsutil/tsutil_test.go, user/search_test.go, user/store.go, user/store_test.go, user/user_test.go
=> tsutil: NewTestClock

user/services/github_test.go
Gist download not allowed in CI test?
=> user: Fix CI
